tensorrt_inference_node: #executable 
  ros__parameters:
    obj_thres: 0.4
    nms_thres: 0.5
    seg_thres: 0.5
    kps_thresh: 0.4112
    num_detect: 20
    detected_class: ["all"]
    model_name: 'yolov8x-seg'

